default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: api_teste_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "myapp_production") %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

cable:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "myapp_production") %>

queue:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "myapp_production") %>

cache:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "myapp_production") %>
