# config/database.yml

default: &default
  adapter: postgresql 
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME","postgres")%>
  password: <%= ENV.fetch("DB_PASSWORD","")%>
  host: <%= ENV.fetch("DB_HOST","localhost")%>

  
development:
  <<: *default
  database: api_teste_development

test:
  <<: *default
  database: api_teste_test


production:
  <<: *default 
  database: api_teste_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>